# NumPy

### Homework

#### Standard Exercises

Before you begin, remember to import the numpy library, if necessary.

In [1]:
import numpy as np

1. Create the following two arrays and print them to screen: 

- a vector `vec1`, containing all the even numbers from 2 to 10, (extremes included)
- a vector `vec2`, containing all the numbers from 1 to 5, (extremes included)

In [2]:
vec1 = np.array([2,4,6,8,10])
vec2 = np.array([1,2,3,4,5])

2. Subrtact `vec2` from `vec1` and save the result in a new vector `vec3`, then print `vec3`

In [3]:
vec3 = vec1 - vec2
print(vec3)

[1 2 3 4 5]


3. Create a new vector `vec4` that is sums the scalar 5 to each element of `vec3`, then print `vec4`

In [4]:
vec4 = vec3 * 5
print(vec4)

[ 5 10 15 20 25]


4. Using vertical stacking, stack `vec3` on top of `vec4` and save the result to a new object named `matrix25`, then print `matrix25`

In [6]:
matrix25 = np.vstack((vec3, vec4))
print(matrix25)

[[ 1  2  3  4  5]
 [ 5 10 15 20 25]]


5. Using slicing, print to the screen the following subsets of `matrix25`: 

- print only the second row of data
- print only the third column of data
- print only the last element of the second row of data

In [11]:
print(matrix25[1])

[ 5 10 15 20 25]


In [12]:
print(matrix25[:, 2])

[ 3 15]


In [13]:
print(matrix25[1, -1])

25


6. Create an array of size 5x5 (a matrix), containing random integer values from 1 to 100; name it `matrix55` and print it

In [26]:
matrix55 = np.random.randint(0,100, (5,5))
print(matrix55)

[[14 55 31 19 45]
 [51 43 30 32 44]
 [61 43 96 98 11]
 [89 26 20 94 68]
 [78 87 65  0 90]]


7. Using three separate statements, print:

- the average of the whole table 
- the sum for each row of the matrix *(hint: you should get 5 results)*
- the maximum value for each column of the matrix *(hint: you should get 5 results)*

*Note: make sure you select the correct axis! [Click here](https://www.sharpsightlabs.com/blog/numpy-axes-explained/) for a refresher.*

In [29]:
print(np.average(matrix55))

51.6


In [30]:
print(sum(matrix55))

[293 254 242 243 258]


In [36]:
print(matrix55.max(axis=0))

[89 87 96 98 90]


8. Use a boolean mask to select only the values in the matrix that are above 50 and save the result in a new object named `mm`, then print `mm`. 

In [37]:
mm = matrix55[matrix55 > 50]
print(mm)

[55 51 61 96 98 89 94 68 78 87 65 90]


9. What is the shape of `mm`? If possible, reshape it to a multi-dimensional array (that is, an object with more than one dimension) and save it to a new object named `mmr`, then print `mmr`. *Note: since we generated `matrix55` using random numbers, your final result may be different from mine and from everyone esle.*

In [46]:
print(mm.shape)

(12,)


In [47]:
mmr = np.reshape(mm, (4, 3))
print(mmr)

[[55 51 61]
 [96 98 89]
 [94 68 78]
 [87 65 90]]


10. Print just the elements of the `mmr` matrix that are even.

In [48]:
print(mmr[mmr % 2 == 0])

[96 98 94 68 78 90]


**If you would like to <font color='green'>continue practicing</font>, visit [this link](https://www.machinelearningplus.com/python/101-numpy-exercises-python/) for a list of 70 numpy exercises with solutions.**

#### Advanced Exercises

1. Replicate the following scheme using the functions and methods we saw in class (not by entering each value by hand)

```
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
```

In [153]:
def evaluate(x, y):
	# print(x % 2 == 0)
	# print(y % 2 == 0)
	test = np.logical_or(x % 2 == 0, y % 2 == 0)
	print(test)
	if (x % 2 == 0 or y % 2 == 0):
		return 1
	else:
		return 0

arr = np.fromfunction(lambda x, y: evaluate(x,y), (5,5), dtype=int)

print(arr)

[[ True  True  True  True  True]
 [ True False  True False  True]
 [ True  True  True  True  True]
 [ True False  True False  True]
 [ True  True  True  True  True]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Before moving to the next question, import the following libraries

In [ ]:
from skimage import io
import matplotlib.pyplot as plt

2. Using the `io.imread()` function, load the `hw_earth.jpg` (from the img folder) image file to a new object named `earth` and show it with the `plt.imshow()` function. 

3. Using the methods seen in class, crop the image as to roughly show only Europe and assign it to a new object named `europe`

4. Using a boolean mask, take the `earth` object and replace all pixels with a value > 200 with a value of 255 (255 = white), this process should slightly increase the contrast of the image; assign this image to a new object named `earth_white`.

5. [<font color='red'>**Difficult**</font>] Take the initial `earth` picture and add the `hw_alien.png` (from the img folder) somewhere in the black void to the left of the earth (you should get something like the screenshot below).

<img src="img/hw_earth-alien-screenshot.png" width="300">